### ISSUE TITLE
Remove vignette?

### ISSUE THREAD

**Issue by DeadMetaler** [mkoura/gnome-shell-darker-overview#1]
Is it possible to remove vignette? It has ugly color banding in gradients.

**Comment by mkoura** [comment]
@DeadMetaler It should be possible, I'll look into it.

**Comment by DeadMetaler** [comment]
@mkoura It would be nice.

**Comment by mkoura** [comment]
Displaying vignette can now be turned off - https://github.com/mkoura/gnome-shell-darker-overview/commit/f12ac01ff49f106c1209393d744d07032edc4741

The new version of the extension is being updated on extensions.gnome.org

**Comment by mkoura** [comment]
Closing the issue as the functionality is already there.
