### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ddnexus** [mkoura/gnome-shell-darker-overview#4]
I don't know whether that is even possible with an extension, but removing the vignette from every place it is used would be a gift for humanity!
(E.g. the authorization modal window background, the shutdown modal window, etc.)
Whould that be possible?

**Comment by mkoura** [comment]
Hey, thanks for suggestion. I think this functionality is out of scope of this extension. This one only modifies the method dealing with the overview.
But nice idea for standalone extension. While I don't mind the vignette, I figured many people hate it 👍

**Comment by ddnexus** [comment]
What about removing it at least from the Overview. That should be in the same scope of the extension...

**Comment by mkoura** [comment]
There's already the "Show vignette" switch in the extension settings. Or do you have something else in mind?

**Comment by ddnexus** [comment]
Ooops! Sorry. It passed a lot of time since I posted the issue, and in my last comment I confuse your extension with a similar one that misses the vignette feature.

I am already using your extension with the vignette disabled. :)
